Perpustakaan/Controllers/BukusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Perpustakaan.Models;

namespace Perpustakaan.Controllers
{
    /// <summary>
    /// Main Class
    /// </summary>
    /// <remarks>
    /// Class ini dapat melakukan CRUD pada Buku.
    /// </remarks>
    public class BukusController : Controller
    {
        /// <summary>
        /// Class controller buku
        /// </summary>
        private readonly PERPUSTAKAAN_PAWContext _context;

        /// <summary>
        /// Menentukan data perpustakaan dapat dibaca.
        /// </summary>
        /// <param name="context"></param>
        public BukusController(PERPUSTAKAAN_PAWContext context)
        {
            _context = context;
        }
        [Authorize(Policy="readonlypolicy")]
        
        /// <summary>
        /// Function untuk GET data buku
        /// </summary>
        /// <param name="ktsd">Parameter ketersediaan</param>
        /// <param name="searchString">Parameter pencarian</param>
        // GET: Bukus
        public async Task<IActionResult> Index(string ktsd, string searchString)
        {
            var ktsdList = new List<string>();
            var ktsdQuery = from d in _context.Buku orderby d.JudulBuku select d.JudulBuku;
            ktsdList.AddRange(ktsdQuery.Distinct());
            ViewBag.ktsd = new SelectList(ktsdList);
            var menu = from m in _context.Buku.Include(k => k.NoKatalogNavigation).Include(k => k.NoRakNavigation) select m;
            if (!string.IsNullOrEmpty(ktsd))
            {
                menu = menu.Where(x => x.JudulBuku == ktsd);
            }
            if (!string.IsNullOrEmpty(searchString))
            {
                menu = menu.Where(s => s.JudulBuku.Contains(searchString) || s.Pengarang.Contains(searchString));
            }
            return View(await menu.ToListAsync());
        }



        /// <summary>
        /// Function untuk GET detail buku
        /// </summary>
        /// <param name="id">Parameter id</param>
        /// <returns>Data Details buku</returns>
        // GET: Bukus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buku = await _context.Buku
                .Include(b => b.NoKatalogNavigation)
                .Include(b => b.NoRakNavigation)
                .FirstOrDefaultAsync(m => m.NoBuku == id);
            if (buku == null)
            {
                return NotFound();
            }

            return View(buku);
        }
        [Authorize(Policy = "writepolicy")]

        /// <summary>
        /// Function untuk GET buku yang akan dibuat
        /// </summary>
        // GET: Bukus/Create
        public IActionResult Create()
        {
            ViewData["NoKatalog"] = new SelectList(_context.KatalogBuku, "NoKatalog", "JenisKatalog");
            ViewData["NoRak"] = new SelectList(_context.Rak, "NoRak", "NamaRak");
            return View();
        }

        /// <summary>
        /// Function untuk POST buku yang akan dibuat
        /// </summary>
        /// <param name="buku">Parameter buku</param>
        /// <returns>Data create buku</returns>
        // POST: Bukus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NoBuku,JudulBuku,NoKatalog,NoRak,Pengarang,Penerbit")] Buku buku)
        {
            if (ModelState.IsValid)
            {
                _context.Add(buku);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["NoKatalog"] = new SelectList(_context.KatalogBuku, "NoKatalog", "NoKatalog", buku.NoKatalog);
            ViewData["NoRak"] = new SelectList(_context.Rak, "NoRak", "NoRak", buku.NoRak);
            return View(buku);
        }
        [Authorize(Policy = "editpolicy")]

        /// <summary>
        /// Function untuk GET buku yang akan diedit
        /// </summary>
        // GET: Bukus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buku = await _context.Buku.FindAsync(id);
            if (buku == null)
            {
                return NotFound();
            }
            ViewData["NoKatalog"] = new SelectList(_context.KatalogBuku, "NoKatalog", "JenisKatalog", buku.NoKatalog);
            ViewData["NoRak"] = new SelectList(_context.Rak, "NoRak", "NamaRak", buku.NoRak);
            return View(buku);
        }

        /// <summary>
        /// Function untuk POST buku yang akan diedit
        /// </summary>
        /// <param name="id">Parameter id</param>
        /// <param name="buku">Parameter buku</param>
        /// <returns>perubahan data buku</returns>
        // POST: Bukus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NoBuku,JudulBuku,NoKatalog,NoRak,Pengarang,Penerbit")] Buku buku)
        {
            if (id != buku.NoBuku)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(buku);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BukuExists(buku.NoBuku))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["NoKatalog"] = new SelectList(_context.KatalogBuku, "NoKatalog", "JenisKatalog", buku.NoKatalog);
            ViewData["NoRak"] = new SelectList(_context.Rak, "NoRak", "NamaRak", buku.NoRak);
            return View(buku);
        }
        [Authorize(Policy = "deletepolicy")]

        /// <summary>
        /// Function untuk GET buku yang akan dihapus
        /// </summary>
        // GET: Bukus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buku = await _context.Buku
                .Include(b => b.NoKatalogNavigation)
                .Include(b => b.NoRakNavigation)
                .FirstOrDefaultAsync(m => m.NoBuku == id);
            if (buku == null)
            {
                return NotFound();
            }

            return View(buku);
        }
        /// <summary>
        /// Function untuk POST buku yang akan dihapus
        /// </summary>
        /// <param name="id"></param>
        /// <returns>penghapusan data buku</returns>
        // POST: Bukus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var buku = await _context.Buku.FindAsync(id);
            _context.Buku.Remove(buku);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BukuExists(int id)
        {
            return _context.Buku.Any(e => e.NoBuku == id);
        }
    }
}

Perpustakaan/Controllers/RaksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Perpustakaan.Models;

namespace Perpustakaan.Controllers
{
    /// <summary>
    /// Main Class
    /// </summary>
    /// <remarks>
    /// Class ini dapat melakukan CRUS pada Rak
    /// </remarks>
    public class RaksController : Controller
    {
        private readonly PERPUSTAKAAN_PAWContext _context;

        /// <summary>
        /// Class Controller Rak
        /// </summary>
        /// <param name="context"></param>
        public RaksController(PERPUSTAKAAN_PAWContext context)
        {
            _context = context;
        }
        /// <summary>
        /// Function untuk GET data Rak
        /// </summary>
        /// <returns>data index rak</returns>
        [Authorize(Policy = "readonlypolicy")]
        // GET: Raks
        public async Task<IActionResult> Index()
        {
            return View(await _context.Rak.ToListAsync());
        }

        // GET: Raks/Details/5
        /// <summary>
        /// Function untuk GET detail rak
        /// </summary>
        /// <param name="id">Parameter Id</param>
        /// <returns>data detail rak</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rak = await _context.Rak
                .FirstOrDefaultAsync(m => m.NoRak == id);
            if (rak == null)
            {
                return NotFound();
            }

            return View(rak);
        }
        /// <summary>
        /// Function untuk GET rak yang akan dibuat
        /// </summary>
        /// <returns>data create rak</returns>
        [Authorize(Policy = "writepolicy")]
        // GET: Raks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Raks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Function untuk POST rak yang akan dibuat
        /// </summary>
        /// <param name="rak"></param>
        /// <returns>data create rak</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NoRak,NamaRak")] Rak rak)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rak);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rak);
        }
        /// <summary>
        /// Function untuk GET Rak yang akan diedit
        /// </summary>
        /// <param name="id"></param>
        /// <returns>perubahan data rak</returns>
        [Authorize(Policy = "editpolicy")]
        // GET: Raks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rak = await _context.Rak.FindAsync(id);
            if (rak == null)
            {
                return NotFound();
            }
            return View(rak);
        }

        // POST: Raks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Function untuk POST Rak yang akan diedit
        /// </summary>
        /// <param name="id">Parameter Id</param>
        /// <param name="rak">Parameter Rak</param>
        /// <returns>perubahan data nomor rak dan nama rak</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NoRak,NamaRak")] Rak rak)
        {
            if (id != rak.NoRak)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rak);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RakExists(rak.NoRak))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rak);
        }
        /// <summary>
        /// Function untuk GET rak yang akan dihapus
        /// </summary>
        /// <param name="id">Parameter Id</param>
        /// <returns>penghapusan data rak</returns>
        [Authorize(Policy = "deletepolicy")]
        // GET: Raks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rak = await _context.Rak
                .FirstOrDefaultAsync(m => m.NoRak == id);
            if (rak == null)
            {
                return NotFound();
            }

            return View(rak);
        }

        // POST: Raks/Delete/5
        /// <summary>
        /// Function untuk POST Rak yang akan dihapus
        /// </summary>
        /// <param name="id">Parameter Id</param>
        /// <returns>penghapusan data rak</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rak = await _context.Rak.FindAsync(id);
            _context.Rak.Remove(rak);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RakExists(int id)
        {
            return _context.Rak.Any(e => e.NoRak == id);
        }
    }
}

Perpustakaan/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Perpustakaan.Controllers
{
    /// <summary>
    /// Main Class
    /// </summary>
    /// <remarks>
    /// Class ini dapat dapat membuat dan menampilkan Index
    /// </remarks>
    public class RoleController : Controller
    {
        /// <summary>
        /// Class role controller
        /// </summary>
        RoleManager<IdentityRole> roleManager;
        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }
      //  [Authorize(Policy = "readonlypolicy")]
      /// <summary>
      /// Function untuk GET data role
      /// </summary>
      /// <returns>
      /// data role
      /// </returns>
        public IActionResult Index()
        {
            var roles = roleManager.Roles.ToList();
            return View(roles);
        }

      //  [Authorize(Policy = "writepolicy")]
      /// <summary>
      /// Function menambahkan index
      /// </summary>
      /// <returns>
      /// data Index
      /// </returns>
        public IActionResult Create()
        {
            return View(new IdentityRole());
        }
        [HttpPost]
        ///<summary>
        ///Function untuk membuat role
        ///</summary> 
        public async Task<IActionResult> Create(IdentityRole role)
        {
            await roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }

    }
}

Perpustakaan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Perpustakaan</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Perpustakaan</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    @if (User.IsInRole("Staff"))
                    {
                        <li><a asp-area="" asp-controller="Role" asp-action="Index">Role</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Daftar Perpustakaan<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Bukus" asp-action="Index">Buku</a></li>
                                <li><a asp-area="" asp-controller="Genders" asp-action="Index">Gender</a></li>
                                <li><a asp-area="" asp-controller="KondisiBukus" asp-action="Index">KondisiBuku</a></li>
                                <li><a asp-area="" asp-controller="Mahasiswas" asp-action="Index">Mahasiswa</a></li>
                                <li><a asp-area="" asp-controller="Peminjamen" asp-action="Index">Peminjamen</a></li>
                                <li><a asp-area="" asp-controller="Pengembalians" asp-action="Index">Pengembalian</a></li>
                                <li><a asp-area="" asp-controller="Raks" asp-action="Index">Rak</a></li>
                                <li><a asp-area="" asp-controller="KatalogBukus" asp-action="Index">Katalog Buku</a></li>
                            </ul>
                        </li>

                    }
                    else if (User.IsInRole("Mahasiswa"))
                    {
                        <li><a asp-area="" asp-controller="Role" asp-action="Index">Role</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Daftar Perpustakaan<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Bukus" asp-action="Index">Buku</a></li>
                           
                                <li><a asp-area="" asp-controller="Peminjamen" asp-action="Index">Peminjamen</a></li>
                                <li><a asp-area="" asp-controller="Pengembalians" asp-action="Index">Pengembalian</a></li>
                               
                            </ul>
                        </li>


                    }

                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2021 - Perpustakaan</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>