Perpustakaan/Models/Mahasiswa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Perpustakaan.Models
{
    /// <summary>
    /// Main class 
    /// </summary>
    /// <remarks>
    /// Class Mahasiswa digunakan untuk verifikasi data mahasiswa yang akan ditambahkan
    /// </remarks>
    public partial class Mahasiswa
    {
        
      
        /// <summary>
        /// Class Mahasiswa
        /// </summary>
        public Mahasiswa()
        {
            Peminjaman = new HashSet<Peminjaman>();
        }


        
        /// <summary>
        /// Untuk verifikasi nomor anggota
        /// </summary>
        public int NoAnggota { get; set; }
       
        /// <summary>
        /// Untuk verifikasi nomor induk mahasiswa
        /// </summary>
        [Required(ErrorMessage = "NIM tidak boleh kosong!!")]
        public string Nim { get; set; }
       
        /// <summary>
        /// Untuk verifikasi nama mahasiswa
        /// </summary>
        [Required(ErrorMessage = "Nama tidak boleh kosong!!")]
        public string Nama { get; set; }
      
        /// <summary>
        /// Untuk verifikasi nomor gender mahasiswa
        /// </summary>
        [Required(ErrorMessage = "No Gender tidak boleh kosong!!")]
        public int? NoGender { get; set; }
       
        /// <summary>
        /// Untuk verifikasi nomor hp mahasiswa
        /// </summary>
        [Required(ErrorMessage = "No Hp tidak boleh kosong!!")]
        public string NoHp { get; set; }
       
        /// <summary>
        /// Untuk verifikasi alamat mahasiswa
        /// </summary>
        [Required(ErrorMessage = "Alamat tidak boleh kosong!!")]
        public string Alamat { get; set; }

        public Gender NoGenderNavigation { get; set; }
        public ICollection<Peminjaman> Peminjaman { get; set; }
    }
}

Perpustakaan/Controllers/MahasiswasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Perpustakaan.Models;

namespace Perpustakaan.Controllers
{
    /// <summary>
    /// Main Class
    /// </summary>
    /// <remarks>
    /// Class ini dapat melakukan CRUD pada Mahasiswa
    /// </remarks>
    public class MahasiswasController : Controller
    {
        private readonly PERPUSTAKAAN_PAWContext _context;

        /// <summary>
        /// Class Controller Mahasiswa
        /// </summary>
        /// <param name="context"></param>
        public MahasiswasController(PERPUSTAKAAN_PAWContext context)
        {
            _context = context;
        }
        /// <summary>
        /// Function untuk GET Mahasiswa
        /// </summary>
        /// <param name="ktsd">parameter ketersediaan</param>
        /// <param name="searchString">parameter pencarian</param>
        /// <returns>data index mahasiswa</returns>
        [Authorize(Policy = "readonlypolicy")]
        // GET: Mahasiswas
        public async Task<IActionResult> Index(string ktsd, string searchString)
        {
            //buat list menyimpan ketersediaan
            var ktsdList = new List<string>();
            //Query mengambil data
            var ktsdQuery = from d in _context.Mahasiswa orderby d.Nama select d.Nama;

            ktsdList.AddRange(ktsdQuery.Distinct());

            //untuk menampilkan di view
            ViewBag.ktsd = new SelectList(ktsdList);

            //panggil db context
            var menu = from m in _context.Mahasiswa.Include(k => k.NoGenderNavigation) select m;

            //untuk memilih dropdownlist ketersediaan
            if (!string.IsNullOrEmpty(ktsd))
            {
                menu = menu.Where(x => x.Nama == ktsd);
            }

            //untuk search data
            if (!string.IsNullOrEmpty(searchString))
            {
                menu = menu.Where(s => s.Nim.Contains(searchString) || s.Nama.Contains(searchString));
            }

            return View(await menu.ToListAsync());
            //var pERPUSTAKAAN_PAWContext = _context.Mahasiswa.Include(m => m.NoGenderNavigation);
            //return View(await pERPUSTAKAAN_PAWContext.ToListAsync());
        }

        // GET: Mahasiswas/Details/5
        /// <summary>
        /// Function untuk GET detail Mahasiswa
        /// </summary>
        /// <param name="id">parameter ID</param>
        /// <returns>
        /// data detail mahasiswa
        /// </returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mahasiswa = await _context.Mahasiswa
                .Include(m => m.NoGenderNavigation)
                .FirstOrDefaultAsync(m => m.NoAnggota == id);
            if (mahasiswa == null)
            {
                return NotFound();
            }

            return View(mahasiswa);
        }
        /// <summary>
        /// Function untuk GET membuat Mahasiswa
        /// </summary>
        /// <returns>data create mahasiswa</returns>
        [Authorize(Policy = "writepolicy")]
        // GET: Mahasiswas/Create
        public IActionResult Create()
        {
            ViewData["NoGender"] = new SelectList(_context.Gender, "NoGender", "NamaGender");
            return View();
        }

        // POST: Mahasiswas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Function untuk POST membuat Mahasiswa
        /// </summary>
        /// <param name="mahasiswa"></param>
        /// <returns>data create mahasiswa</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NoAnggota,Nim,Nama,NoGender,NoHp,Alamat")] Mahasiswa mahasiswa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mahasiswa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["NoGender"] = new SelectList(_context.Gender, "NoGender", "NamaGender", mahasiswa.NoGender);
            return View(mahasiswa);
        }
        /// <summary>
        /// Function untuk GET mahasiswa yang akan di edit
        /// </summary>
        /// <param name="id">parameter id</param>
        /// <returns>perubahan data mahasiswa</returns>
        [Authorize(Policy = "editpolicy")]
        // GET: Mahasiswas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mahasiswa = await _context.Mahasiswa.FindAsync(id);
            if (mahasiswa == null)
            {
                return NotFound();
            }
            ViewData["NoGender"] = new SelectList(_context.Gender, "NoGender", "NamaGender", mahasiswa.NoGender);
            return View(mahasiswa);
        }

        // POST: Mahasiswas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Function untuk POST Mahasiswa yang akan diedit
        /// </summary>
        /// <param name="id">parameter id</param>
        /// <param name="mahasiswa">parameter mahasiswa</param>
        /// <returns>
        /// perubahan data mahasiswa
        /// </returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NoAnggota,Nim,Nama,NoGender,NoHp,Alamat")] Mahasiswa mahasiswa)
        {
            if (id != mahasiswa.NoAnggota)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mahasiswa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MahasiswaExists(mahasiswa.NoAnggota))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["NoGender"] = new SelectList(_context.Gender, "NoGender", "NamaGender", mahasiswa.NoGender);
            return View(mahasiswa);
        }
        /// <summary>
        /// Function untuk GET Mahasiswa yang akan dihapus
        /// </summary>
        /// <param name="id"></param>
        /// <returns>pernghapusan data mahasiswa</returns>
        [Authorize(Policy = "deletepolicy")]
        // GET: Mahasiswas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mahasiswa = await _context.Mahasiswa
                .Include(m => m.NoGenderNavigation)
                .FirstOrDefaultAsync(m => m.NoAnggota == id);
            if (mahasiswa == null)
            {
                return NotFound();
            }

            return View(mahasiswa);
        }

        // POST: Mahasiswas/Delete/5
        /// <summary>
        /// Function untuk POST Mahasiswa yang akan dihapus
        /// </summary>
        /// <param name="id"></param>
        /// <returns>
        /// penghapusan data Mahasiswa
        /// </returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mahasiswa = await _context.Mahasiswa.FindAsync(id);
            _context.Mahasiswa.Remove(mahasiswa);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MahasiswaExists(int id)
        {
            return _context.Mahasiswa.Any(e => e.NoAnggota == id);
        }
    }
}

Perpustakaan/Views/Mahasiswas/Create.cshtml
@model Perpustakaan.Models.Mahasiswa

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Mahasiswa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nim" class="control-label"></label>
                <input asp-for="Nim" class="form-control" />
                <span asp-validation-for="Nim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nama" class="control-label"></label>
                <input asp-for="Nama" class="form-control" />
                <span asp-validation-for="Nama" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoGenderNavigation.NamaGender" class="control-label"></label>
                <select asp-for="NoGender" class ="form-control" asp-items="ViewBag.NoGender"></select>
            </div>
            <div class="form-group">
                <label asp-for="NoHp" class="control-label"></label>
                <input asp-for="NoHp" class="form-control" />
                <span asp-validation-for="NoHp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alamat" class="control-label"></label>
                <input asp-for="Alamat" class="form-control" />
                <span asp-validation-for="Alamat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Perpustakaan/Views/Mahasiswas/Delete.cshtml
@model Perpustakaan.Models.Mahasiswa

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Mahasiswa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nim)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nim)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nama)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nama)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoHp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoHp)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Alamat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Alamat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoGenderNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoGenderNavigation.NoGender)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="NoAnggota" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Perpustakaan/Views/Mahasiswas/Details.cshtml
@model Perpustakaan.Models.Mahasiswa

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Mahasiswa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nim)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nim)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nama)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nama)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoHp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoHp)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Alamat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Alamat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoGenderNavigation.NamaGender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoGenderNavigation.NamaGender)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.NoAnggota">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Perpustakaan/Views/Mahasiswas/Edit.cshtml
@model Perpustakaan.Models.Mahasiswa

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Mahasiswa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="NoAnggota" />
            <div class="form-group">
                <label asp-for="Nim" class="control-label"></label>
                <input asp-for="Nim" class="form-control" />
                <span asp-validation-for="Nim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nama" class="control-label"></label>
                <input asp-for="Nama" class="form-control" />
                <span asp-validation-for="Nama" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoGender" class="control-label"></label>
                <select asp-for="NoGender" class="form-control" asp-items="ViewBag.NoGender"></select>
                <span asp-validation-for="NoGender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoHp" class="control-label"></label>
                <input asp-for="NoHp" class="form-control" />
                <span asp-validation-for="NoHp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alamat" class="control-label"></label>
                <input asp-for="Alamat" class="form-control" />
                <span asp-validation-for="Alamat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Perpustakaan/Views/Mahasiswas/Index.cshtml
@model IEnumerable<Perpustakaan.Models.Mahasiswa>

@{
    ViewData["Title"] = "Index";
}

<h2>Mahasiswa</h2>

<p>
    <a asp-action="Create">Tambah Data</a>
</p>
@using (Html.BeginForm("Index", "Mahasiswas", FormMethod.Get))
{
    <p>
        Nama Mahasiswa: @Html.DropDownList("ktsd", "Nama Mahasiswa")
        Cari Data : @Html.TextBox("searchString")
        <input type="submit" value="Filter" />
    </p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nama)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoHp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Alamat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoGenderNavigation.NamaGender)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Nim)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Nama)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.NoHp)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Alamat)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.NoGenderNavigation.NamaGender)
    </td>
    <td>
        <a asp-action="Edit" asp-route-id="@item.NoAnggota">Edit</a> |
        <a asp-action="Details" asp-route-id="@item.NoAnggota">Details</a> |
        <a asp-action="Delete" asp-route-id="@item.NoAnggota">Delete</a>
    </td>
</tr>
}
    </tbody>
</table>