Perpustakaan/Controllers/PeminjamenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Perpustakaan.Models;

namespace Perpustakaan.Controllers
{
    /// <summary>
    /// Main Class
    /// </summary>
    /// <remask>
    /// Class ini dapat melakukan CRUD pada Peminjaman
    /// </remask>
    public class PeminjamenController : Controller
    {
        private readonly PERPUSTAKAAN_PAWContext _context;

        /// <summary>
        /// Class Controller Peminjaman
        /// </summary>
        /// <param name="context"></param>
        public PeminjamenController(PERPUSTAKAAN_PAWContext context)
        {
            _context = context;
        }

        // GET: Peminjamen
        /// <summary>
        /// Function untuk GET data Peminjaman
        /// </summary>
        /// <param name="ktsd">Parameter ketersediaan</param>
        /// <param name="searchString">Parameter pencarian</param>
        /// <returns>data index peminjaman</returns>
        [Authorize(Policy="readonlypolicy")]
        public async Task<IActionResult> Index(string ktsd, string searchString)
        {
            //buat list menyimpan ketersediaan
            var ktsdList = new List<string>();
            //Query mengambil data
            var ktsdQuery = from d in _context.Peminjaman orderby d.NoAnggotaNavigation.Nama select d.NoAnggotaNavigation.Nama;

            ktsdList.AddRange(ktsdQuery.Distinct());

            //untuk menampilkan di view
            ViewBag.ktsd = new SelectList(ktsdList);

            //panggil db context
            var menu = from m in _context.Peminjaman.Include(k => k.NoBukuNavigation).Include(k => k.NoAnggotaNavigation) select m;

            //untuk memilih dropdownlist ketersediaan
            if (!string.IsNullOrEmpty(ktsd))
            {
                menu = menu.Where(x => x.NoAnggotaNavigation.Nama == ktsd);
            }

            //untuk search data
            if (!string.IsNullOrEmpty(searchString))
            {
                menu = menu.Where(s => s.TglPeminjaman.ToString().Contains(searchString) || s.NoAnggotaNavigation.Nama.Contains(searchString) || s.NoBukuNavigation.JudulBuku.Contains(searchString));
            }

            return View(await menu.ToListAsync());
            //var pERPUSTAKAAN_PAWContext = _context.Peminjaman.Include(p => p.NoAnggotaNavigation).Include(p => p.NoBukuNavigation);
            //return View(await pERPUSTAKAAN_PAWContext.ToListAsync());
        }

        // GET: Peminjamen/Details/5
        /// <summary>
        /// Function GET detail peminjaman
        /// </summary>
        /// <param name="id">Paramter Id</param>
        /// <returns>data detail peminjaman</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var peminjaman = await _context.Peminjaman
                .Include(p => p.NoAnggotaNavigation)
                .Include(p => p.NoBukuNavigation)
                .FirstOrDefaultAsync(m => m.NoPeminjaman == id);
            if (peminjaman == null)
            {
                return NotFound();
            }

            return View(peminjaman);
        }

        /// <summary>
        /// Function untuk GET peminjaman yang akan dibuat
        /// </summary>
        /// <returns>data create peminjaman</returns>
        [Authorize(Policy = "writepolicy")]
        // GET: Peminjamen/Create
        public IActionResult Create()
        {
            ViewData["NoAnggota"] = new SelectList(_context.Mahasiswa, "NoAnggota", "Nama");
            ViewData["NoBuku"] = new SelectList(_context.Buku, "NoBuku", "JudulBuku");
            return View();
        }

        // POST: Peminjamen/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Funtion untuk POST peminjaman yang akan dibuat
        /// </summary>
        /// <param name="peminjaman"></param>
        /// <returns>data create peminjaman</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NoPeminjaman,TglPeminjaman,NoBuku,NoAnggota")] Peminjaman peminjaman)
        {
            if (ModelState.IsValid)
            {
                _context.Add(peminjaman);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["NoAnggota"] = new SelectList(_context.Mahasiswa, "NoAnggota", "Nama", peminjaman.NoAnggota);
            ViewData["NoBuku"] = new SelectList(_context.Buku, "NoBuku", "JudulBuku", peminjaman.NoBuku);
            return View(peminjaman);
        }

        /// <summary>
        /// Function untuk GET peminjaman yang akan diedit
        /// </summary>
        /// <param name="id">Parameter ID</param>
        /// <returns>perubahan data peminjaman</returns>
        [Authorize(Policy = "editpolicy")]
        // GET: Peminjamen/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var peminjaman = await _context.Peminjaman.FindAsync(id);
            if (peminjaman == null)
            {
                return NotFound();
            }
            ViewData["NoAnggota"] = new SelectList(_context.Mahasiswa, "NoAnggota", "Nama", peminjaman.NoAnggota);
            ViewData["NoBuku"] = new SelectList(_context.Buku, "NoBuku", "JudulBuku", peminjaman.NoBuku);
            return View(peminjaman);
        }

        // POST: Peminjamen/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Function untuk POST peminjaman yang akan diedit
        /// </summary>
        /// <param name="id">Parameter Id</param>
        /// <param name="peminjaman">Parameter Peminjaman</param>
        /// <returns>perubahan nomor peminjaman ,tanggal peminjaman. nomor buku dan nomor anggota</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NoPeminjaman,TglPeminjaman,NoBuku,NoAnggota")] Peminjaman peminjaman)
        {
            if (id != peminjaman.NoPeminjaman)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(peminjaman);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PeminjamanExists(peminjaman.NoPeminjaman))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["NoAnggota"] = new SelectList(_context.Mahasiswa, "NoAnggota", "Nama", peminjaman.NoAnggota);
            ViewData["NoBuku"] = new SelectList(_context.Buku, "NoBuku", "JudulBuku", peminjaman.NoBuku);
            return View(peminjaman);
        }

        /// <summary>
        /// Function untuk GET peminjamnan yang akan dihapus
        /// </summary>
        /// <param name="id">Parameter id</param>
        /// <returns>penghapusan data peminjaman</returns>
        [Authorize(Policy = "deletepolicy")]
        // GET: Peminjamen/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var peminjaman = await _context.Peminjaman
                .Include(p => p.NoAnggotaNavigation)
                .Include(p => p.NoBukuNavigation)
                .FirstOrDefaultAsync(m => m.NoPeminjaman == id);
            if (peminjaman == null)
            {
                return NotFound();
            }

            return View(peminjaman);
        }

        // POST: Peminjamen/Delete/5
        /// <summary>
        /// Function untuk POST peminjaman yang akan dihapus
        /// </summary>
        /// <param name="id">Parameter id</param>
        /// <returns>penghapusan data peminjaman</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var peminjaman = await _context.Peminjaman.FindAsync(id);
            _context.Peminjaman.Remove(peminjaman);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PeminjamanExists(int id)
        {
            return _context.Peminjaman.Any(e => e.NoPeminjaman == id);
        }
    }
}

Perpustakaan/Views/Peminjamen/Create.cshtml
@model Perpustakaan.Models.Peminjaman

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Peminjaman</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TglPeminjaman" class="control-label"></label>
                <input asp-for="TglPeminjaman" class="form-control" />
                <span asp-validation-for="TglPeminjaman" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoBukuNavigation.JudulBuku" class="control-label"></label>
                <select asp-for="NoBuku" class ="form-control" asp-items="ViewBag.NoBuku"></select>
            </div>
            <div class="form-group">
                <label asp-for="NoAnggotaNavigation.Nama" class="control-label"></label>
                <select asp-for="NoAnggota" class ="form-control" asp-items="ViewBag.NoAnggota"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Perpustakaan/Views/Peminjamen/Delete.cshtml
@model Perpustakaan.Models.Peminjaman

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Peminjaman</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TglPeminjaman)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TglPeminjaman)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoAnggotaNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoAnggotaNavigation.NoAnggota)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoBukuNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoBukuNavigation.NoBuku)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="NoPeminjaman" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Perpustakaan/Views/Peminjamen/Details.cshtml
@model Perpustakaan.Models.Peminjaman

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Peminjaman</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TglPeminjaman)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TglPeminjaman)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoAnggotaNavigation.Nama)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoAnggotaNavigation.Nama)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoBukuNavigation.JudulBuku)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoBukuNavigation.JudulBuku)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.NoPeminjaman">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Perpustakaan/Views/Peminjamen/Edit.cshtml
@model Perpustakaan.Models.Peminjaman

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Peminjaman</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="NoPeminjaman" />
            <div class="form-group">
                <label asp-for="TglPeminjaman" class="control-label"></label>
                <input asp-for="TglPeminjaman" class="form-control" />
                <span asp-validation-for="TglPeminjaman" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoBuku" class="control-label"></label>
                <select asp-for="NoBuku" class="form-control" asp-items="ViewBag.NoBuku"></select>
                <span asp-validation-for="NoBuku" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoAnggota" class="control-label"></label>
                <select asp-for="NoAnggota" class="form-control" asp-items="ViewBag.NoAnggota"></select>
                <span asp-validation-for="NoAnggota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Perpustakaan/Views/Peminjamen/Index.cshtml
@model IEnumerable<Perpustakaan.Models.Peminjaman>

@{
    ViewData["Title"] = "Index";
}

<h2>Peminjaman</h2>

<p>
    <a asp-action="Create">Tambah Data</a>
</p>
@using (Html.BeginForm("Index", "Peminjamen", FormMethod.Get))
{
    <p>
        Nama Peminjam: @Html.DropDownList("ktsd", "Nama Peminjam")
        Cari Data : @Html.TextBox("searchString")
        <input type="submit" value="Filter" />
    </p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TglPeminjaman)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoAnggotaNavigation.Nama)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoBukuNavigation.JudulBuku)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TglPeminjaman)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NoAnggotaNavigation.Nama)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NoBukuNavigation.JudulBuku)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.NoPeminjaman">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.NoPeminjaman">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.NoPeminjaman">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>