Perpustakaan/Models/Pengembalian.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Perpustakaan.Models
{
    /// <summary>
    /// Main Class
    /// </summary>
    /// <remarks>
    /// Class Pengembalian digunakan untuk verifikasi data pengembalian yang akan dimasukan
    /// </remarks>
    public partial class Pengembalian
    {
        /// <summary>
        /// Untuk verifikasi Nomor Pengembalian
        /// </summary>
        public int NoPengembalian { get; set; }
        /// <summary>
        /// Untuk verifikasi Tanggal pengembalian
        /// </summary>
        [Required(ErrorMessage = "Tanggal Pengembalian tidak boleh kosong!!")]
        public DateTime? TglPengembalian { get; set; }
        /// <summary>
        /// Untuk verifikasi Nomor kondisi
        /// </summary>
        [Required(ErrorMessage = "No Kondisi tidak boleh kosong!!")]
        public int? NoKondisi { get; set; }
        /// <summary>
        /// Untuk verifikasi Denda
        /// </summary>
        [Required(ErrorMessage = "Denda tidak boleh kosong!!")]
        public int? Denda { get; set; }
        /// <summary>
        /// Untuk verifikasi Nomor peminjaman
        /// </summary>
        [Required(ErrorMessage = "No Peminjaman tidak boleh kosong!!")]
        public int? NoPeminjaman { get; set; }

        public KondisiBuku NoKondisiNavigation { get; set; }
        public Peminjaman NoPeminjamanNavigation { get; set; }
    }
}

Perpustakaan/Controllers/PengembaliansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Perpustakaan.Models;

namespace Perpustakaan.Controllers
{
    /// <summary>
    /// Main Class
    /// </summary>
    /// <remarks>
    /// Class ini dapat melakukan CRUD pada Pengembalian
    /// </remarks>
    public class PengembaliansController : Controller
    {
        private readonly PERPUSTAKAAN_PAWContext _context;

        /// <summary>
        /// Class Controller Pengembalian
        /// </summary>
        /// <param name="context"></param>
        public PengembaliansController(PERPUSTAKAAN_PAWContext context)
        {
            _context = context;
        }
        /// <summary>
        /// Function untuk GET data Pengembalian
        /// </summary>
        /// <param name="ktsd"></param>
        /// <param name="searchString"></param>
        /// <returns>data index</returns>
        [Authorize(Policy = "readonlypolicy")]

        // GET: Pengembalians
        public async Task<IActionResult> Index(string ktsd, string searchString)
        {
            //buat list menyimpan ketersediaan
            var ktsdList = new List<string>();
            //Query mengambil data
            var ktsdQuery = from d in _context.Pengembalian orderby d.NoPeminjaman.ToString() select d.NoPeminjaman.ToString();

            ktsdList.AddRange(ktsdQuery.Distinct());

            //untuk menampilkan di view
            ViewBag.ktsd = new SelectList(ktsdList);

            //panggil db context
            var menu = from m in _context.Pengembalian.Include(k => k.NoKondisiNavigation).Include(k => k.NoPeminjamanNavigation) select m;

            //untuk memilih dropdownlist ketersediaan
            if (!string.IsNullOrEmpty(ktsd))
            {
                menu = menu.Where(x => x.NoPeminjaman.ToString() == ktsd);
            }

            //untuk search data
            if (!string.IsNullOrEmpty(searchString))
            {
                menu = menu.Where(s => s.NoPeminjaman.ToString().Contains(searchString));
            }

            return View(await menu.ToListAsync());
            //var pERPUSTAKAAN_PAWContext = _context.Pengembalian.Include(p => p.NoKondisiNavigation).Include(p => p.NoPeminjamanNavigation);
            //return View(await pERPUSTAKAAN_PAWContext.ToListAsync());
        }

        // GET: Pengembalians/Details/5
        /// <summary>
        /// Function untuk GET detail pengembalian
        /// </summary>
        /// <param name="id"></param>
        /// <returns>data detail pengembalian</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pengembalian = await _context.Pengembalian
                .Include(p => p.NoKondisiNavigation)
                .Include(p => p.NoPeminjamanNavigation)
                .FirstOrDefaultAsync(m => m.NoPengembalian == id);
            if (pengembalian == null)
            {
                return NotFound();
            }

            return View(pengembalian);
        }
        /// <summary>
        /// Function untuk GET Pengembalian yang akan dibuat
        /// </summary>
        /// <returns>data create pengembalian</returns>
        [Authorize(Policy = "writepolicy")]
        // GET: Pengembalians/Create
        public IActionResult Create()
        {
            ViewData["NoKondisi"] = new SelectList(_context.KondisiBuku, "NoKondisi", "NamaKondisi");
            ViewData["NoPeminjaman"] = new SelectList(_context.Peminjaman, "NoPeminjaman", "NoPeminjaman");
            return View();
        }

        // POST: Pengembalians/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Function untuk POST pengembalian yang akan dibuat
        /// </summary>
        /// <param name="pengembalian">Parameter pengembalian</param>
        /// <returns>data create pengembalian</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NoPengembalian,TglPengembalian,NoKondisi,Denda,NoPeminjaman")] Pengembalian pengembalian)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pengembalian);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["NoKondisi"] = new SelectList(_context.KondisiBuku, "NoKondisi", "NamaKondisi", pengembalian.NoKondisi);
            ViewData["NoPeminjaman"] = new SelectList(_context.Peminjaman, "NoPeminjaman", "NoPeminjaman", pengembalian.NoPeminjaman);
            return View(pengembalian);
        }
        /// <summary>
        /// Function untuk GET peminjaman yang akan diedit
        /// </summary>
        /// <param name="id"></param>
        /// <returns>perubahan data pengembalian</returns>
        [Authorize(Policy = "editpolicy")]
        // GET: Pengembalians/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pengembalian = await _context.Pengembalian.FindAsync(id);
            if (pengembalian == null)
            {
                return NotFound();
            }
            ViewData["NoKondisi"] = new SelectList(_context.KondisiBuku, "NoKondisi", "NamaKondisi", pengembalian.NoKondisi);
            ViewData["NoPeminjaman"] = new SelectList(_context.Peminjaman, "NoPeminjaman", "NoPeminjaman", pengembalian.NoPeminjaman);
            return View(pengembalian);
        }

        // POST: Pengembalians/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Function untuk POST pengembalian yang akan diedit
        /// </summary>
        /// <param name="id">Parameter Id</param>
        /// <param name="pengembalian">Parameter Pengembalian</param>
        /// <returns>perubahan nomor pengembalian , tanggal pengembalian , nomor kondisi , dena dan nomor peminjaman</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NoPengembalian,TglPengembalian,NoKondisi,Denda,NoPeminjaman")] Pengembalian pengembalian)
        {
            if (id != pengembalian.NoPengembalian)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pengembalian);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PengembalianExists(pengembalian.NoPengembalian))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["NoKondisi"] = new SelectList(_context.KondisiBuku, "NoKondisi", "NamaKondisi", pengembalian.NoKondisi);
            ViewData["NoPeminjaman"] = new SelectList(_context.Peminjaman, "NoPeminjaman", "NoPeminjaman", pengembalian.NoPeminjaman);
            return View(pengembalian);
        }
        /// <summary>
        /// Function untuk GET pengembalian yang akan dihapus
        /// </summary>
        /// <param name="id">Parameter Id</param>
        /// <returns>penghapusan data pengembalian</returns>
        [Authorize(Policy = "deletepolicy")]
        // GET: Pengembalians/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pengembalian = await _context.Pengembalian
                .Include(p => p.NoKondisiNavigation)
                .Include(p => p.NoPeminjamanNavigation)
                .FirstOrDefaultAsync(m => m.NoPengembalian == id);
            if (pengembalian == null)
            {
                return NotFound();
            }

            return View(pengembalian);
        }

        // POST: Pengembalians/Delete/5
        /// <summary>
        /// Function untuk POST pengembalian yang akan dihapus
        /// </summary>
        /// <param name="id">Parameter Id</param>
        /// <returns>penghapusan data pengembalian</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pengembalian = await _context.Pengembalian.FindAsync(id);
            _context.Pengembalian.Remove(pengembalian);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PengembalianExists(int id)
        {
            return _context.Pengembalian.Any(e => e.NoPengembalian == id);
        }
    }
}

Perpustakaan/Views/Pengembalians/Create.cshtml
@model Perpustakaan.Models.Pengembalian

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Pengembalian</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TglPengembalian" class="control-label"></label>
                <input asp-for="TglPengembalian" class="form-control" />
                <span asp-validation-for="TglPengembalian" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoKondisiNavigation.NamaKondisi" class="control-label"></label>
                <select asp-for="NoKondisi" class ="form-control" asp-items="ViewBag.NoKondisi"></select>
            </div>
            <div class="form-group">
                <label asp-for="Denda" class="control-label"></label>
                <input asp-for="Denda" class="form-control" />
                <span asp-validation-for="Denda" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoPeminjaman" class="control-label"></label>
                <select asp-for="NoPeminjaman" class ="form-control" asp-items="ViewBag.NoPeminjaman"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Perpustakaan/Views/Pengembalians/Delete.cshtml
@model Perpustakaan.Models.Pengembalian

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pengembalian</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TglPengembalian)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TglPengembalian)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Denda)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Denda)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoKondisiNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoKondisiNavigation.NoKondisi)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoPeminjamanNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoPeminjamanNavigation.NoPeminjaman)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="NoPengembalian" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Perpustakaan/Views/Pengembalians/Details.cshtml
@model Perpustakaan.Models.Pengembalian

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pengembalian</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TglPengembalian)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TglPengembalian)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Denda)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Denda)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoKondisiNavigation.NamaKondisi)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoKondisiNavigation.NamaKondisi)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoPeminjamanNavigation.NoPeminjaman)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoPeminjamanNavigation.NoPeminjaman)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.NoPengembalian">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Perpustakaan/Views/Pengembalians/Edit.cshtml
@model Perpustakaan.Models.Pengembalian

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Pengembalian</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="NoPengembalian" />
            <div class="form-group">
                <label asp-for="TglPengembalian" class="control-label"></label>
                <input asp-for="TglPengembalian" class="form-control" />
                <span asp-validation-for="TglPengembalian" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoKondisi" class="control-label"></label>
                <select asp-for="NoKondisi" class="form-control" asp-items="ViewBag.NoKondisi"></select>
                <span asp-validation-for="NoKondisi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Denda" class="control-label"></label>
                <input asp-for="Denda" class="form-control" />
                <span asp-validation-for="Denda" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoPeminjaman" class="control-label"></label>
                <select asp-for="NoPeminjaman" class="form-control" asp-items="ViewBag.NoPeminjaman"></select>
                <span asp-validation-for="NoPeminjaman" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Perpustakaan/Views/Pengembalians/Index.cshtml
@model IEnumerable<Perpustakaan.Models.Pengembalian>

@{
    ViewData["Title"] = "Index";
}

<h2>Pengembalian</h2>

<p>
    <a asp-action="Create">Tambah Data</a>
</p>
@using (Html.BeginForm("Index", "Pengembalians", FormMethod.Get))
{
    <p>
        No Peminjaman: @Html.DropDownList("ktsd", "No Peminjaman")
        Cari Data : @Html.TextBox("searchString")
        <input type="submit" value="Filter" />
    </p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TglPengembalian)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Denda)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoKondisiNavigation.NamaKondisi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoPeminjamanNavigation.NoPeminjaman)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TglPengembalian)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Denda)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NoKondisiNavigation.NamaKondisi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NoPeminjamanNavigation.NoPeminjaman)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.NoPengembalian">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.NoPengembalian">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.NoPengembalian">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>